# Generated by Django 4.0 on 2022-05-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionDescriptionHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=9)),
                ('t_header', models.CharField(max_length=9)),
                ('t_text', models.CharField(max_length=9)),
                ('b_header', models.CharField(max_length=9)),
                ('b_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VersionMinecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VersionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('allservers', 'Allservers'), ('pcclassic', 'Pcclassic'), ('pcmods', 'Pcmods'), ('bedrock', 'Bedrock'), ('newservers', 'Newservers')], max_length=20)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.versiondescriptionhtml')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.versionminecraft', verbose_name='minecraft version')),
            ],
        ),
    ]
