# Generated by Django 4.0 on 2022-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiondescriptionhtml',
            name='b_header',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='versiondescriptionhtml',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='versiondescriptionhtml',
            name='t_header',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='versiondescriptionhtml',
            name='t_text',
            field=models.CharField(max_length=550),
        ),
    ]
